// styles/GroceryListStyles.js
import { StyleSheet } from "react-native";
import { colors, fonts } from "./theme";
import {
  scale,
  verticalScale,
  moderateScale,
  normalizeFont,
} from "../utils/sizes";

export const styles = StyleSheet.create({
  safeAreaView: {
    flex: 1,
    backgroundColor: colors.background,
  },
  stickyHeaderContainer: {
    backgroundColor: colors.navyBlue,
    paddingVertical: verticalScale(8),
    paddingHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightCream,
    zIndex: 10,
    width: "100%",
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: scale(20),
    marginBottom: verticalScale(10),
  },
  title: {
    fontSize: fonts.titleSize,
    fontFamily: fonts.main,
    fontWeight: "bold",
    color: colors.lightCream,
    marginBottom: verticalScale(10),
  },
  savingIndicator: {
    color: colors.lightCream,
    fontStyle: "italic",
    fontSize: normalizeFont(12),
    marginBottom: 0,
    textAlign: "right",
    height: verticalScale(20),
    borderRadius: moderateScale(6),
    lineHeight: verticalScale(20),
  },
  columnHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingRight: scale(8),
  },
  checkboxHeader: {
    width: scale(24),
    marginRight: scale(12),
  },
  firstTableColumnText: {
    flex: 2,
    textAlign: "left",
    color: colors.lightCream,
    fontWeight: "bold",
    paddingLeft: scale(23),
    fontSize: normalizeFont(16),
  },
  tableColumnText: {
    flex: 1,
    textAlign: "center",
    color: colors.lightCream,
    fontWeight: "bold",
    fontSize: normalizeFont(16),
  },
  deleteBtnColumn: {
    width: scale(65),
  },
  scrollViewContent: {
    paddingHorizontal: scale(16),
    paddingBottom: verticalScale(40),
    backgroundColor: colors.navyBlue,
    flexGrow: 1,
  },
  keyboardAwareViewStyle: {
    paddingBottom: verticalScale(50),
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.2)",
    paddingVertical: verticalScale(10),
    paddingRight: scale(8),
  },
  checkboxHeader: {
    width: scale(24),
    marginRight: scale(12),
  },
  checkboxChecked: {
    backgroundColor: colors.lightCream,
    justifyContent: "center",
    alignItems: "center",
  },
  itemNameInput: {
    flex: 2,
    height: verticalScale(30),
    borderBottomWidth: 0,
    borderColor: "transparent",
    paddingHorizontal: scale(6),
    color: colors.lightCream,
    backgroundColor: "transparent",
    fontSize: normalizeFont(16),
  },
  itemPcsInput: {
    flex: 1,
    textAlign: "center",
    height: verticalScale(30),
    borderBottomWidth: 0,
    borderColor: "transparent",
    paddingHorizontal: scale(6),
    color: colors.lightCream,
    backgroundColor: "transparent",
    fontSize: normalizeFont(16),
  },
  itemPriceInput: {
    flex: 1,
    textAlign: "center",
    height: verticalScale(30),
    borderBottomWidth: 0,
    borderColor: "transparent",
    paddingHorizontal: scale(6),
    color: colors.lightCream,
    backgroundColor: "transparent",
    fontSize: normalizeFont(16),
  },
  deleteBtnCircle: {
    backgroundColor: colors.darkPink,
    width: scale(36),
    height: scale(36),
    borderRadius: scale(18),
    justifyContent: "center",
    alignItems: "center",
    marginLeft: scale(6),
  },
  footerSticky: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.navyBlue,
    paddingVertical: verticalScale(12),
    paddingHorizontal: scale(20),
    borderTopWidth: 1,
    borderColor: colors.lightCream,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  totalText: {
    fontSize: normalizeFont(20),
    fontWeight: "bold",
    color: colors.lightCream,
    fontFamily: fonts.main,
  },
  addButton: {
    backgroundColor: colors.darkPink,
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(18),
    borderRadius: moderateScale(8),
  },
  addButtonText: {
    color: colors.lightCream,
    fontWeight: "bold",
    fontSize: normalizeFont(16),
  },
});
