// styles/styles.js
import { StyleSheet } from "react-native";
import {
  scale,
  verticalScale,
  moderateScale,
  normalizeFont,
} from "../utils/sizes";

export const navyBlue = "#0c2d5d";
export const lightCream = "#e8e5d9";
export const darkPink = "#781d4e";
export const mainFont = "Montserrat";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: scale(20),
    backgroundColor: navyBlue,
  },
  safeAreaView: {
    flex: 1,
    backgroundColor: navyBlue,
  },
  centerContainer: {
    flex: 1,
    padding: scale(20),
    justifyContent: "center",
    backgroundColor: navyBlue,
  },
  input: {
    height: verticalScale(40),
    borderWidth: 1,
    borderRadius: moderateScale(10),
    paddingHorizontal: scale(15),
    backgroundColor: "#fff",
    marginBottom: verticalScale(10),
    width: "100%",
  },
  title: {
    fontSize: normalizeFont(40),
    fontFamily: mainFont,
    fontWeight: "bold",
    textAlign: "left",
    color: lightCream,
    marginBottom: verticalScale(30),
  },
  pageTitle: {
    fontSize: normalizeFont(40),
    fontFamily: mainFont,
    fontWeight: "bold",
    color: lightCream,
    marginBottom: 0,
    flex: 1,
  },
  subtitle: {
    fontSize: normalizeFont(30),
    textAlign: "center",
    color: lightCream,
    fontFamily: mainFont,
    marginBottom: verticalScale(16),
  },
  bodyText: {
    fontSize: normalizeFont(16),
    color: lightCream,
    fontFamily: mainFont,
    marginBottom: verticalScale(16),
  },
  loginSignUpButton: {
    backgroundColor: lightCream,
    borderWidth: 1,
    paddingVertical: verticalScale(14),
    borderRadius: moderateScale(10),
    alignItems: "center",
    marginVertical: verticalScale(10),
    width: "100%",
  },
  buttonText: {
    color: navyBlue,
    fontSize: normalizeFont(16),
    fontWeight: "bold",
  },
  linkText: {
    marginTop: verticalScale(14),
    fontSize: normalizeFont(14),
    color: lightCream,
    textAlign: "center",
  },
  linkTextHighlight: {
    color: darkPink,
    fontWeight: "600",
  },
  navBar: {
    backgroundColor: lightCream,
    borderTopWidth: 0,
    height: verticalScale(55),
    paddingBottom: verticalScale(5),
    paddingTop: verticalScale(5),
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  calendarWrapper: {
    backgroundColor: navyBlue,
    padding: scale(5),
    marginBottom: verticalScale(5),
  },
  calendarTheme: {
    backgroundColor: navyBlue,
    calendarBackground: navyBlue,
    dayTextColor: lightCream,
    monthTextColor: lightCream,
    textSectionTitleColor: lightCream,
    selectedDayTextColor: lightCream,
    todayTextColor: lightCream,
    arrowColor: lightCream,

    textDayFontSize: normalizeFont(17),
    textMonthFontSize: normalizeFont(17),
    textDayHeaderFontSize: normalizeFont(14),
  },
  divider: {
    height: 1,
    backgroundColor: "#ccc",
    marginBottom: verticalScale(20),
  },
  fabContainer: {
    position: "absolute",
    bottom: verticalScale(30),
    right: scale(30),
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  fabButton: {
    backgroundColor: lightCream,
    borderRadius: moderateScale(30),
    width: scale(60),
    height: scale(60),
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: darkPink,
    fontSize: normalizeFont(14),
    marginBottom: verticalScale(8),
    fontFamily: mainFont,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    backgroundColor: lightCream,
    padding: scale(20),
    borderRadius: moderateScale(12),
    width: "85%",
  },
  modalTitle: {
    fontSize: normalizeFont(18),
    fontWeight: "bold",
    marginBottom: verticalScale(12),
    color: navyBlue,
  },
  modalSubtitle: {
    color: navyBlue,
    marginBottom: verticalScale(8),
    fontWeight: "600",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: verticalScale(10),
  },
  categoryScroll: {
    marginBottom: verticalScale(12),
  },
  categoryButton: {
    backgroundColor: lightCream,
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(14),
    borderRadius: moderateScale(20),
    marginRight: scale(10),
    borderWidth: 1,
    borderColor: navyBlue,
  },
  categoryButtonSelected: {
    backgroundColor: navyBlue,
  },
  categoryButtonText: {
    color: navyBlue,
    fontWeight: "normal",
  },
  categoryButtonTextSelected: {
    color: lightCream,
    fontWeight: "bold",
  },
  customCategoryRow: {
    flexDirection: "row",
    marginBottom: verticalScale(12),
    alignItems: "center",
  },
  customCategoryInput: {
    flex: 1,
    height: verticalScale(40),
    borderColor: navyBlue,
    borderWidth: 1,
    borderRadius: moderateScale(8),
    paddingHorizontal: scale(10),
    color: navyBlue,
  },
  addCategoryButton: {
    marginLeft: scale(10),
    backgroundColor: navyBlue,
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(15),
    borderRadius: moderateScale(8),
  },
  addCategoryButtonDisabled: {
    backgroundColor: "#999",
  },
  addCategoryButtonText: {
    color: lightCream,
    fontWeight: "bold",
  },
  cancelButton: {
    marginRight: scale(20),
  },
  cancelButtonText: {
    color: navyBlue,
  },
  saveButtonText: {
    color: navyBlue,
    fontWeight: "bold",
  },
  sectionHeader: {
    backgroundColor: navyBlue,
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(12),
    borderRadius: moderateScale(6),
    marginBottom: verticalScale(12),
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  sectionHeaderText: {
    color: lightCream,
    fontWeight: "bold",
    fontSize: normalizeFont(18),
  },
  collapseArrow: {
    color: lightCream,
    fontWeight: "bold",
    fontSize: normalizeFont(18),
    marginRight: scale(8),
  },
  expenseItem: {
    backgroundColor: lightCream,
    padding: scale(16),
    borderRadius: moderateScale(10),
    marginBottom: verticalScale(10),
    flexDirection: "row",
  },
  expenseText: {
    color: navyBlue,
    fontSize: normalizeFont(16),
    fontFamily: mainFont,
  },
  expenseItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  expenseDescription: {
    flex: 1,
    fontWeight: "600",
  },
  expenseAmount: {
    fontWeight: "bold",
    fontSize: normalizeFont(16),
  },
  dayTotalContainer: {
    backgroundColor: lightCream,
    marginBottom: verticalScale(10),
    paddingVertical: verticalScale(12),
    paddingHorizontal: scale(16),
    alignItems: "center",
    borderRadius: moderateScale(10),
  },
  dayTotalText: {
    fontSize: normalizeFont(16),
    fontWeight: "bold",
    color: navyBlue,
  },
  reminderItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: verticalScale(14),
    paddingHorizontal: scale(12),
    backgroundColor: lightCream,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  deleteBtn: {
    backgroundColor: darkPink,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  deleteBtnNoBg: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderColor: lightCream,
  },
  swipeDeleteButton: {
    backgroundColor: darkPink,
    justifyContent: "center",
    alignItems: "center",
    width: scale(70),
    height: "100%",
    borderRadius: moderateScale(8),
    marginVertical: verticalScale(8),
    marginRight: scale(8),
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: scale(16),
    marginBottom: verticalScale(10),
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: scale(25),
    marginBottom: verticalScale(10),
  },
  keyboardAwareViewStyle: {
    paddingBottom: verticalScale(50),
  },

  profileText: {
    fontSize: normalizeFont(16),
    color: lightCream,
    fontFamily: mainFont,
    marginBottom: verticalScale(8),
  },
  tabBarContainer: {
    alignItems: "center",
    marginTop: verticalScale(10),
    marginBottom: verticalScale(5),
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#fff2",
    borderRadius: verticalScale(20),
    overflow: "hidden",
    width: 220,
    height: 38,
    elevation: 2,
  },
  tabPill: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: verticalScale(8),
    borderRadius: verticalScale(0),
    backgroundColor: "transparent",
    marginHorizontal: scale(2),
    height: "100%",
  },
  tabPillActive: {
    backgroundColor: "#e8e5d9",
  },
  tabPillLeftActive: {
    borderTopLeftRadius: verticalScale(20),
    borderBottomLeftRadius: verticalScale(20),
  },
  tabPillRightActive: {
    borderTopRightRadius: verticalScale(20),
    borderBottomRightRadius: verticalScale(20),
  },
  tabPillText: {
    color: "#e8e5d9",
    fontWeight: "bold",
    fontSize: normalizeFont(14),
  },
  tabPillTextActive: {
    color: "#0c2d5d",
  },
  scrollViewContent: {
    paddingHorizontal: scale(16),
    paddingBottom: verticalScale(40),
    backgroundColor: navyBlue,
    flexGrow: 1,
  },
  profileInfoContainer: {
    marginBottom: verticalScale(10),
    marginTop: verticalScale(10),
  },
  logoutButton: {
    backgroundColor: lightCream,
    borderRadius: moderateScale(8),
    marginBottom: verticalScale(10),
    alignSelf: "center",
    width: "95%",
    height: verticalScale(30),
    justifyContent: "center",
    alignItems: "center",
  },
  logoutButtonText: {
    color: lightCream,
    fontWeight: "bold",
    fontSize: normalizeFont(14),
  },
  tabContent: {
    flexGrow: 1,
    minHeight: verticalScale(400),
  },
  statsScrollContent: {
    paddingBottom: verticalScale(40),
  },
  statsSectionHeader: {
    fontWeight: "bold",
    fontSize: normalizeFont(18),
    marginBottom: verticalScale(10),
  },
  statsBudgetLabel: {
    fontWeight: "normal",
    fontSize: normalizeFont(14),
    color: "#fff9",
  },
  statsBarChart: {
    marginVertical: verticalScale(8),
    borderRadius: moderateScale(16),
  },
  monthPickerContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: verticalScale(10),
    flexWrap: "wrap",
  },
  monthPickerButton: {
    paddingVertical: verticalScale(6),
    paddingHorizontal: scale(12),
    borderRadius: moderateScale(16),
    backgroundColor: "#fff2",
    marginHorizontal: scale(3),
    marginBottom: verticalScale(5),
  },
  monthPickerButtonActive: {
    backgroundColor: "#781d4e",
  },
  monthPickerText: {
    color: "#e8e5d9",
    fontSize: normalizeFont(14),
  },
  monthPickerTextActive: {
    color: "#e8e5d9",
    fontWeight: "bold",
    fontSize: normalizeFont(14),
  },
  yearPickerContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: verticalScale(10),
  },
  yearPickerButton: {
    paddingVertical: verticalScale(6),
    paddingHorizontal: scale(14),
    borderRadius: moderateScale(16),
    backgroundColor: "#fff2",
    marginHorizontal: scale(3),
  },
  yearPickerButtonActive: {
    backgroundColor: "#781d4e",
  },
  yearPickerText: {
    color: "#e8e5d9",
    fontSize: normalizeFont(14),
  },
  yearPickerTextActive: {
    color: "#e8e5d9",
    fontWeight: "bold",
    fontSize: normalizeFont(14),
  },
  statsCategoryHeader: {
    marginTop: verticalScale(24),
  },
});
