// styles/styles.js
import { StyleSheet } from "react-native";
import {
  scale,
  verticalScale,
  moderateScale,
  normalizeFont,
} from "../utils/sizes";

export const navyBlue = "#0c2d5d";
export const lightCream = "#e8e5d9";
export const darkPink = "#781d4e";
export const mainFont = "Montserrat";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: scale(20),
    backgroundColor: navyBlue,
  },
  safeAreaView: {
    flex: 1,
    backgroundColor: navyBlue,
  },
  centerContainer: {
    flex: 1,
    padding: scale(20),
    justifyContent: "center",
    backgroundColor: navyBlue,
  },
  input: {
    height: verticalScale(40),
    borderWidth: 1,
    borderRadius: moderateScale(10),
    paddingHorizontal: scale(15),
    backgroundColor: "#fff",
    marginBottom: verticalScale(10),
    width: "100%",
  },
  title: {
    fontSize: normalizeFont(40),
    fontFamily: mainFont,
    fontWeight: "bold",
    textAlign: "left",
    color: lightCream,
    marginBottom: verticalScale(30),
  },
  pageTitle: {
    fontSize: normalizeFont(40),
    fontFamily: mainFont,
    fontWeight: "bold",
    color: lightCream,
    marginBottom: 0,
    flex: 1,
  },
  subtitle: {
    fontSize: normalizeFont(30),
    textAlign: "center",
    color: lightCream,
    fontFamily: mainFont,
    marginBottom: verticalScale(16),
  },
  bodyText: {
    fontSize: normalizeFont(16),
    color: lightCream,
    fontFamily: mainFont,
    marginBottom: verticalScale(16),
  },
  button: {
    backgroundColor: lightCream,
    borderWidth: 1,
    paddingVertical: verticalScale(14),
    borderRadius: moderateScale(10),
    alignItems: "center",
    marginVertical: verticalScale(10),
    width: "100%",
  },
  buttonText: {
    color: navyBlue,
    fontSize: normalizeFont(16),
    fontWeight: "bold",
  },
  linkText: {
    marginTop: verticalScale(14),
    fontSize: normalizeFont(14),
    color: lightCream,
    textAlign: "center",
  },
  linkTextHighlight: {
    color: darkPink,
    fontWeight: "600",
  },
  navBar: {
    backgroundColor: lightCream,
    borderTopWidth: 0,
    height: verticalScale(55),
    paddingBottom: verticalScale(5),
    paddingTop: verticalScale(5),
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  calendarWrapper: {
    backgroundColor: navyBlue,
    padding: scale(5),
    marginBottom: verticalScale(5),
  },
  calendarTheme: {
    backgroundColor: navyBlue,
    calendarBackground: navyBlue,
    dayTextColor: lightCream,
    monthTextColor: lightCream,
    textSectionTitleColor: lightCream,
    selectedDayTextColor: lightCream,
    todayTextColor: lightCream,
    arrowColor: lightCream,

    textDayFontSize: normalizeFont(17),
    textMonthFontSize: normalizeFont(17),
    textDayHeaderFontSize: normalizeFont(14),
  },
  divider: {
    height: 1,
    backgroundColor: "#ccc",
    marginBottom: verticalScale(20),
  },
  fabContainer: {
    position: "absolute",
    bottom: verticalScale(30),
    right: scale(30),
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  fabButton: {
    backgroundColor: lightCream,
    borderRadius: moderateScale(30),
    width: scale(60),
    height: scale(60),
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: darkPink,
    fontSize: normalizeFont(14),
    marginBottom: verticalScale(8),
    fontFamily: mainFont,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    backgroundColor: lightCream,
    padding: scale(20),
    borderRadius: moderateScale(12),
    width: "85%",
  },
  modalTitle: {
    fontSize: normalizeFont(18),
    fontWeight: "bold",
    marginBottom: verticalScale(12),
    color: navyBlue,
  },
  modalSubtitle: {
    color: navyBlue,
    marginBottom: verticalScale(8),
    fontWeight: "600",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: verticalScale(10),
  },
  categoryScroll: {
    marginBottom: verticalScale(12),
  },
  categoryButton: {
    backgroundColor: lightCream,
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(14),
    borderRadius: moderateScale(20),
    marginRight: scale(10),
    borderWidth: 1,
    borderColor: navyBlue,
  },
  categoryButtonSelected: {
    backgroundColor: navyBlue,
  },
  categoryButtonText: {
    color: navyBlue,
    fontWeight: "normal",
  },
  categoryButtonTextSelected: {
    color: lightCream,
    fontWeight: "bold",
  },
  customCategoryRow: {
    flexDirection: "row",
    marginBottom: verticalScale(12),
    alignItems: "center",
  },
  customCategoryInput: {
    flex: 1,
    height: verticalScale(40),
    borderColor: navyBlue,
    borderWidth: 1,
    borderRadius: moderateScale(8),
    paddingHorizontal: scale(10),
    color: navyBlue,
  },
  addCategoryButton: {
    marginLeft: scale(10),
    backgroundColor: navyBlue,
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(15),
    borderRadius: moderateScale(8),
  },
  addCategoryButtonDisabled: {
    backgroundColor: "#999",
  },
  addCategoryButtonText: {
    color: lightCream,
    fontWeight: "bold",
  },
  cancelButton: {
    marginRight: scale(20),
  },
  cancelButtonText: {
    color: navyBlue,
  },
  saveButtonText: {
    color: navyBlue,
    fontWeight: "bold",
  },
  sectionHeader: {
    backgroundColor: navyBlue,
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(12),
    borderRadius: moderateScale(6),
    marginBottom: verticalScale(12),
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  sectionHeaderText: {
    color: lightCream,
    fontWeight: "bold",
    fontSize: normalizeFont(18),
  },
  collapseArrow: {
    color: lightCream,
    fontWeight: "bold",
    fontSize: normalizeFont(18),
    marginRight: scale(8),
  },
  expenseItem: {
    backgroundColor: lightCream,
    padding: scale(16),
    borderRadius: moderateScale(10),
    marginBottom: verticalScale(10),
    flexDirection: "row",
  },
  expenseText: {
    color: navyBlue,
    fontSize: normalizeFont(16),
    fontFamily: mainFont,
  },
  expenseItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  expenseDescription: {
    flex: 1,
    fontWeight: "600",
  },
  expenseAmount: {
    fontWeight: "bold",
    fontSize: normalizeFont(16),
  },
  dayTotalContainer: {
    backgroundColor: lightCream,
    marginBottom: verticalScale(10),
    paddingVertical: verticalScale(12),
    paddingHorizontal: scale(16),
    alignItems: "center",
    borderRadius: moderateScale(10),
  },
  dayTotalText: {
    fontSize: normalizeFont(16),
    fontWeight: "bold",
    color: navyBlue,
  },
  reminderItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: verticalScale(14),
    paddingHorizontal: scale(12),
    backgroundColor: lightCream,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  deleteBtn: {
    backgroundColor: darkPink,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  deleteBtnNoBg: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderColor: lightCream,
  },
  totalText: {
    fontSize: normalizeFont(20),
    fontWeight: "bold",
    color: lightCream,
    fontFamily: mainFont,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.2)",
    paddingVertical: verticalScale(10),
  },
  groceryListInput: {
    flex: 1,
    height: verticalScale(30),
    borderBottomWidth: 0,
    borderColor: "transparent",
    paddingHorizontal: scale(6),
    color: lightCream,
    backgroundColor: "transparent",
    fontSize: normalizeFont(16),
  },
  checkbox: {
    width: scale(24),
    height: scale(24),
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: lightCream,
    justifyContent: "center",
    alignItems: "center",
    marginRight: scale(12),
  },
  checkboxChecked: {
    backgroundColor: lightCream,
    justifyContent: "center",
    alignItems: "center",
  },
  swipeDeleteButton: {
    backgroundColor: darkPink,
    justifyContent: "center",
    alignItems: "center",
    width: scale(70),
    height: "100%",
    borderRadius: moderateScale(8),
    marginVertical: verticalScale(8),
    marginRight: scale(8),
  },
  deleteBtnCircle: {
    backgroundColor: darkPink,
    width: scale(36),
    height: scale(36),
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: scale(6),
  },
  footerSticky: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: navyBlue,
    paddingVertical: verticalScale(12),
    paddingHorizontal: scale(20),
    borderTopWidth: 1,
    borderColor: lightCream,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  addButton: {
    backgroundColor: darkPink,
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(18),
    borderRadius: moderateScale(8),
  },
  addButtonText: {
    color: lightCream,
    fontWeight: "bold",
    fontSize: normalizeFont(16),
  },
  savingIndicator: {
    color: lightCream,
    fontStyle: "italic",
    fontSize: normalizeFont(12),
    marginBottom: 0,
    textAlign: "right",
    height: verticalScale(20),
    borderRadius: moderateScale(6),
    lineHeight: verticalScale(20),
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: scale(16),
    marginBottom: verticalScale(10),
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: scale(25),
    marginBottom: verticalScale(10),
  },
  stickyHeaderContainer: {
    backgroundColor: navyBlue,
    paddingVertical: verticalScale(8),
    paddingHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: lightCream,
    zIndex: 10,
    width: "100%",
  },
  columnHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkboxHeader: {
    width: 24,
    marginRight: 12,
  },
  columnHeaderText: {
    color: lightCream,
    fontWeight: "bold",
    fontSize: normalizeFont(16),
  },
});
